DET_SOURCE_DIR: '/mnt/LocalDisk1/Projects/AIC21-MTMC/datasets/algorithm_results/detection/images/test/S06/'
REID_MODEL: 'reid_model/resnet101_ibn_a_3.pth'
REID_BACKBONE: 'resnet101_ibn_a'
DET_IMG_DIR: '/mnt/LocalDisk1/Projects/AIC21-MTMC/datasets/algorithm_results/detect_merge/'
DATA_DIR: '/mnt/LocalDisk1/Projects/AIC21-MTMC/datasets/algorithm_results/detect_reid3/'
REID_SIZE_TEST: [384, 384]
